"""Regenerate the bend-aware copies of the four outline shaders.

    python Tools/gen_bent_outline_shaders.py            # write RetroXR/Shaders/outline*_bent.gdshader
    python Tools/gen_bent_outline_shaders.py --check    # exit 1 if any copy is out of step

A book's pick-up outline has to bend with the book (RetroXR/Shaders/outline_flop.gdshaderinc).
The four outline shaders have a history of taking a Quest's GPU down when their SHAPE
changes (see their headers: VRS + stencil, constant-folded fragment outputs), so they are not
touched and not restructured: every other object keeps byte-for-byte the shader it had, and
only the book gets a copy with the bend spliced in between two marker lines.

A copy of a fragile file drifts. Run this after editing any outline*.gdshader;
book_flop_tests strips the marked lines back out of each copy and compares it with its
original, so a copy that was not regenerated goes red in CI.
"""
import pathlib
import sys

SHADERS = pathlib.Path(__file__).resolve().parent.parent / "RetroXR" / "Shaders"
BEGIN = "// --- bent (Tools/gen_bent_outline_shaders.py) ---"
END = "// --- end bent ---"
INCLUDE_LINE = '#include "res://Shaders/outline_flop.gdshaderinc"'
# Every added line, blank ones included, sits BETWEEN the markers, so stripping the
# marked blocks gives back the original exactly.
INCLUDE = [BEGIN, INCLUDE_LINE, "", END]
CALL = [
    "\t" + BEGIN,
    "\tvec3 bent_vertex = VERTEX;",
    "\tvec3 bent_normal = NORMAL;",
    "\toutline_flop(bent_vertex, bent_normal);",
    "\tVERTEX = bent_vertex;",
    "\tNORMAL = bent_normal;",
    "\t" + END,
]
HEADER = [
    "// GENERATED by Tools/gen_bent_outline_shaders.py from {name} — do not edit.",
    "// The same shader with a book's bend (outline_flop.gdshaderinc) run on the vertex",
    "// first; everything else, comments included, is the original's. Edit THAT and",
    "// regenerate.",
    "//",
]


def bent(name: str, text: str) -> str:
    crlf = "\r\n" in text
    lines = text.replace("\r\n", "\n").split("\n")
    out = [h.format(name=name) for h in HEADER]
    has_vertex = any(l.startswith("void vertex()") for l in lines)
    for line in lines:
        if line.startswith("void vertex()"):
            out += INCLUDE
            out.append(line)
            out += CALL
            continue
        if line.startswith("void fragment()") and not has_vertex:
            # The mask pass has no vertex stage of its own: give it one.
            out += [BEGIN, INCLUDE_LINE, "", "void vertex() {"]
            out += [l for l in CALL if l.strip() not in (BEGIN, END)]
            out += ["}", "", END]
        out.append(line)
    result = "\n".join(out)
    return result.replace("\n", "\r\n") if crlf else result


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for src in sorted(SHADERS.glob("outline*.gdshader")):
        if src.stem.endswith("_bent"):
            continue
        dst = src.with_name(src.stem + "_bent.gdshader")
        want = bent(src.name, src.read_text(encoding="utf-8"))
        have = dst.read_text(encoding="utf-8") if dst.exists() else None
        if have != want:
            stale.append(dst.name)
            if not check:
                dst.write_text(want, encoding="utf-8", newline="")
                print("wrote", dst.name)
    if check and stale:
        print("out of step with their originals:", ", ".join(stale))
        return 1
    if not stale:
        print("all four bent outline shaders are in step")
    return 0


if __name__ == "__main__":
    sys.exit(main())
