"""Build RetroXR's table of which N64 games save to a Controller Pak.

The source is mupen64plus-libretro-nx's compiled ROM database, the header the core
actually builds from, so the table agrees with the core that runs the game:

    python Tools/gen_n64_save_db.py
    python Tools/gen_n64_save_db.py --ini path/to/mupen64plus.ini.h

Two facts come out of it, each keyed by ROM MD5 (what RomM reports) and by the
header CRC pair (what a local file can be read for without hashing it):

  uses_pak  the database says Mempak=Yes
  pak_only  Mempak=Yes and SaveType=None -- the cartridge keeps nothing

The database marks no game Mempak=No and treats a missing line as "may use one",
so a game absent from uses_pak is unknown, not a game without a pak.
"""

import argparse
import os
import re
import sys

DEFAULT_INI = os.path.expanduser(
    "~/libretro-cores-retroxr/mupen64plus-libretro-nx/custom/mupen64plus-core/main/mupen64plus.ini.h")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "RetroXR",
                   "Scripts", "Data", "n64_save_db_table.gd")

# Games that save to a Controller Pak and carry no Mempak line in the database.
# F-Zero X keeps its ghosts on a pak. Matched on GoodName prefix, so every dump
# of the release is covered; the iQue build has no controller port for one.
EXTRA_USES_PAK = ("F-ZERO X (E)", "F-ZERO X (J)", "F-ZERO X (U)")


def read_entries(path):
    entries = {}
    current = None
    with open(path, encoding="latin-1") as f:
        for raw in f:
            raw = raw.strip()
            if not raw.startswith('"'):
                continue
            line = raw[1:]
            if line.endswith('\\n"'):
                line = line[:-3]
            elif line.endswith('"'):
                line = line[:-1]
            line = line.replace('\\"', '"')
            m = re.fullmatch(r"\[([0-9A-Fa-f]{32})\]", line)
            if m:
                current = {"md5": m.group(1).lower()}
                entries[current["md5"]] = current
                continue
            if current is None or "=" not in line or line.startswith(";"):
                continue
            key, value = line.split("=", 1)
            current[key] = value
    return entries


def resolved(entries, entry, key):
    if key in entry:
        return entry[key]
    ref = entry.get("RefMD5", "").lower()
    if ref and ref in entries:
        return entries[ref].get(key)
    return None


def crc_key(entry, entries):
    crc = resolved(entries, entry, "CRC")
    if not crc:
        return None
    parts = crc.upper().split()
    return "%s-%s" % (parts[0], parts[1]) if len(parts) == 2 else None


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--ini", default=DEFAULT_INI)
    parser.add_argument("--out", default=OUT)
    args = parser.parse_args()
    if not os.path.isfile(args.ini):
        sys.exit("no ROM database at %s" % args.ini)

    entries = read_entries(args.ini)
    uses, only = {}, {}
    for md5, e in entries.items():
        name = resolved(entries, e, "GoodName") or ""
        pak = resolved(entries, e, "Mempak") == "Yes" or name.startswith(EXTRA_USES_PAK)
        uses[md5] = pak
        only[md5] = pak and resolved(entries, e, "SaveType") == "None"

    # A CRC pair is shared by a release and its hacks and bad dumps. It only
    # answers when every entry under it agrees.
    def by_crc(flags):
        votes = {}
        for md5, e in entries.items():
            k = crc_key(e, entries)
            if k:
                votes.setdefault(k, set()).add(flags[md5])
        return sorted(k for k, v in votes.items() if v == {True})

    tables = {
        "USES_PAK_MD5": sorted(m for m, v in uses.items() if v),
        "PAK_ONLY_MD5": sorted(m for m, v in only.items() if v),
        "USES_PAK_CRC": by_crc(uses),
        "PAK_ONLY_CRC": by_crc(only),
    }

    out = ["## Generated by Tools/gen_n64_save_db.py from mupen64plus-libretro-nx's ROM",
           "## database. Do not edit; re-run the script.",
           "class_name N64SaveDbTable", ""]
    for name, keys in tables.items():
        out.append("const %s := {" % name)
        out.extend('\t"%s": true,' % k for k in keys)
        out.append("}")
        out.append("")
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out))
    for name, keys in tables.items():
        print("%-13s %d" % (name, len(keys)))


if __name__ == "__main__":
    main()
